# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-10 15:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateTimeField(verbose_name='date issued')),
                ('return_date', models.DateTimeField(verbose_name='date to return the product')),
                ('is_returned', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProductsSupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker_app.ProductsSupplier'),
        ),
        migrations.AddField(
            model_name='issues',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker_app.Products'),
        ),
        migrations.AddField(
            model_name='issues',
            name='product_supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker_app.ProductsSupplier'),
        ),
    ]
