# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-10 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0002_auto_20170810_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='product',
            field=models.ForeignKey(db_column='productID', on_delete=django.db.models.deletion.CASCADE, to='tracker_app.Product'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='product_supplier',
            field=models.ForeignKey(db_column='productsupplierID', on_delete=django.db.models.deletion.CASCADE, to='tracker_app.ProductSupplier'),
        ),
    ]
