# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-10 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0003_auto_20170810_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker_app.Product'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='product_supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker_app.ProductSupplier'),
        ),
    ]
